### PR TITLE
Add PRNG Security Layer (9999-bit PRNG password generator for password security)

### PR DESCRIPTION
**Pull request by ghost**
Not sure if this will help Spotlight, but it can do decent password security for adding the password into the config.

### CODE REVIEW

**Comment by ghost** [comment]
I see some bugs in my code, gimme a few mins and I will fix em :)

**Comment by spotlightishere** [comment]
If there's documentation on a place asides from pwgen, I'd rather it be from openssl or similarly approved cryptographic generators. Additionally having such a high byte count adds quite a lot of unneeded complexity.

**Comment by ghost** [comment]
Alr then :) Hey speaking of which Spotlight, I'm nearly there on getting the shop engine done, I am about 3/4 of the way. Also speaking of which, I might actually repurpose this code for the Wii Room shop engine I'm making actually. The only thing that it requires is the Owncloud panel, which is the keystore for the initial decryption of webhook urls, which then locally decrypts the password, which then in turn decrypts the pickled file. Webhook URL's, Datadog API key's, and Printful confirm offsets are the main things it encrypts 😄 This is in case someone gets SSH access to cacti, they can't decrypt that stuff without owncloud access.

**Comment by Peter0x44** [comment]
The random module is a pseudorandom number generator.
Even the python documentation tells you *not* to use this for any security purposes
https://docs.python.org/3/library/random.html

**Comment by ghost** [comment]
Yeah Ik, my security bot caught that @urmum-69, I'm still learning how to do encryption in python. ;p

**Pull request closed without merging**
